<?php

namespace Database\Seeders;

// use Illuminate\Database\Console\Seeds\WithoutModelEvents;

use App\Models\Ditmawa;
use App\Models\UKM;
use App\Models\User;
use Illuminate\Database\Seeder;

class DatabaseSeeder extends Seeder
{
    /**
     * Seed the application's database.
     */
    public function run(): void
    {
        User::insert([
            ["username" => "teluesport",
            "password" => bcrypt("password"),
            "role" => "ukm"],
            ["username" => "123456789",
            "password" => bcrypt("password"),
            "role" => "ditmawa"]
        ]);

        UKM::insert([
            ["nama_ukm" => "Telkom University Esports",
            "jenis_ukm" => "Olahraga",
            "logo_ukm" => "telkom-university-esports.png",
            "status_ukm" => "aktif"],
            ["nama_ukm" => "UKM Aceh",
            "jenis_ukm" => "Kesenian & Kebudayaan",
            "logo_ukm" => "ukm-aceh.png",
            "status_ukm" => "aktif"],
            ["nama_ukm" => "AVi Pictures",
            "jenis_ukm" => "Kesenian & Kebudayaan",
            "logo_ukm" => "avi-pictures.png",
            "status_ukm" => "aktif"],
            ["nama_ukm" => "Balon Kata",
            "jenis_ukm" => "Kesenian & Kebudayaan",
            "logo_ukm" => "balon-kata.png",
            "status_ukm" => "aktif"],
            ["nama_ukm" => "UKM Band",
            "jenis_ukm" => "Kesenian & Kebudayaan",
            "logo_ukm" => "ukm-band.png",
            "status_ukm" => "aktif"],
            ["nama_ukm" => "Djawa Tjap Parabola",
            "jenis_ukm" => "Kesenian & Kebudayaan",
            "logo_ukm" => "djawa-tjap-parabola.png",
            "status_ukm" => "aktif"],
            ["nama_ukm" => "Bengkel Seni Embun",
            "jenis_ukm" => "Kesenian & Kebudayaan",
            "logo_ukm" => "bengkel-seni-embun.png",
            "status_ukm" => "aktif"],
            ["nama_ukm" => "Fotografi Telkom",
            "jenis_ukm" => "Kesenian & Kebudayaan",
            "logo_ukm" => "fotografi-telkom.png",
            "status_ukm" => "aktif"],
            ["nama_ukm" => "UKM Kalimantan",
            "jenis_ukm" => "Kesenian & Kebudayaan",
            "logo_ukm" => "ukm-kalimantan.png",
            "status_ukm" => "aktif"],
            ["nama_ukm" => "KBMS",
            "jenis_ukm" => "Kesenian & Kebudayaan",
            "logo_ukm" => "kbms.png",
            "status_ukm" => "aktif"],
            ["nama_ukm" => "UKM Kesenian Bali",
            "jenis_ukm" => "Kesenian & Kebudayaan",
            "logo_ukm" => "ukm-kesenian-bali.png",
            "status_ukm" => "aktif"],
            ["nama_ukm" => "Nippon Bunka-BU",
            "jenis_ukm" => "Kesenian & Kebudayaan",
            "logo_ukm" => "nippon-bunka-bu.png",
            "status_ukm" => "aktif"],
            ["nama_ukm" => "Telkom University Choir",
            "jenis_ukm" => "Kesenian & Kebudayaan",
            "logo_ukm" => "telkom-university-choir.png",
            "status_ukm" => "aktif"],
            ["nama_ukm" => "PERMALA",
            "jenis_ukm" => "Kesenian & Kebudayaan",
            "logo_ukm" => "permala.png",
            "status_ukm" => "aktif"],
            ["nama_ukm" => "Rumah Gadang",
            "jenis_ukm" => "Kesenian & Kebudayaan",
            "logo_ukm" => "rumah-gadang.png",
            "status_ukm" => "aktif"],
            ["nama_ukm" => "SAMALOWA",
            "jenis_ukm" => "Kesenian & Kebudayaan",
            "logo_ukm" => "samalowa.png",
            "status_ukm" => "aktif"],
            ["nama_ukm" => "SAWANDA",
            "jenis_ukm" => "Kesenian & Kebudayaan",
            "logo_ukm" => "sawanda.png",
            "status_ukm" => "aktif"],
            ["nama_ukm" => "Teater Titik",
            "jenis_ukm" => "Kesenian & Kebudayaan",
            "logo_ukm" => "teater-titik.png",
            "status_ukm" => "aktif"],
            ["nama_ukm" => "IMMAPA",
            "jenis_ukm" => "Kesenian & Kebudayaan",
            "logo_ukm" => "immapa.png",
            "status_ukm" => "aktif"],
            ["nama_ukm" => "Telkom University Badminton",
            "jenis_ukm" => "Olahraga",
            "logo_ukm" => "telkom-university-badminton.png",
            "status_ukm" => "aktif"],
            ["nama_ukm" => "UKM Bola",
            "jenis_ukm" => "Olahraga",
            "logo_ukm" => "ukm-bola.png",
            "status_ukm" => "aktif"],
            ["nama_ukm" => "UKM Bola Basket",
            "jenis_ukm" => "Olahraga",
            "logo_ukm" => "ukm-bola-basket.png",
            "status_ukm" => "aktif"],
            ["nama_ukm" => "Capoeira Brazil Telkom University",
            "jenis_ukm" => "Olahraga",
            "logo_ukm" => "capoeira-brazil-telkom-university.png",
            "status_ukm" => "aktif"],
            ["nama_ukm" => "Persatuan Catur Mahasiswa",
            "jenis_ukm" => "Olahraga",
            "logo_ukm" => "persatuan-catur-mahasiswa.png",
            "status_ukm" => "aktif"],
            ["nama_ukm" => "Karate",
            "jenis_ukm" => "Olahraga",
            "logo_ukm" => "karate.png",
            "status_ukm" => "aktif"],
            ["nama_ukm" => "Riverside Softball",
            "jenis_ukm" => "Olahraga",
            "logo_ukm" => "riverside-softball.png",
            "status_ukm" => "aktif"],
            ["nama_ukm" => "PPS Betako Merpati Putih",
            "jenis_ukm" => "Olahraga",
            "logo_ukm" => "pps-betako-merah-putih.png",
            "status_ukm" => "aktif"],
            ["nama_ukm" => "Voli Tel-U / TVBC",
            "jenis_ukm" => "Olahraga",
            "logo_ukm" => "voli-telu.png",
            "status_ukm" => "aktif"],
            ["nama_ukm" => "Teaekwondo",
            "jenis_ukm" => "Olahraga",
            "logo_ukm" => "taekwondo.png",
            "status_ukm" => "aktif"],
            ["nama_ukm" => "Archery Academy of Telkom University",
            "jenis_ukm" => "Olahraga",
            "logo_ukm" => "archatel.png",
            "status_ukm" => "aktif"],
            ["nama_ukm" => "Aksara Jurnalistik",
            "jenis_ukm" => "Penalaran",
            "logo_ukm" => "aksara-jurnalistik.png",
            "status_ukm" => "aktif"],
            ["nama_ukm" => "Central Computer Improvement",
            "jenis_ukm" => "Penalaran",
            "logo_ukm" => "central-computer-improvement.png",
            "status_ukm" => "aktif"],
            ["nama_ukm" => "HIPMI PT",
            "jenis_ukm" => "Penalaran",
            "logo_ukm" => "hipmi-pt.png",
            "status_ukm" => "aktif"],
            ["nama_ukm" => "Indonesia Marketing Association",
            "jenis_ukm" => "Penalaran",
            "logo_ukm" => "ima.png",
            "status_ukm" => "aktif"],
            ["nama_ukm" => "IEEE",
            "jenis_ukm" => "Penalaran",
            "logo_ukm" => "ieee.png",
            "status_ukm" => "aktif"],
            ["nama_ukm" => "KOPMA Tel-U",
            "jenis_ukm" => "Penalaran",
            "logo_ukm" => "kopma-telu.png",
            "status_ukm" => "aktif"],
            ["nama_ukm" => "SEARCH",
            "jenis_ukm" => "Penalaran",
            "logo_ukm" => "search.png",
            "status_ukm" => "aktif"],
            ["nama_ukm" => "SES",
            "jenis_ukm" => "Penalaran",
            "logo_ukm" => "ses.png",
            "status_ukm" => "aktif"],
            ["nama_ukm" => "Persatuan Mahasiswa Kristen",
            "jenis_ukm" => "Kerohanian",
            "logo_ukm" => "persatuan-mahasiswa-kristen.png",
            "status_ukm" => "aktif"],
            ["nama_ukm" => "Keluarga Mahasiswa Katolik",
            "jenis_ukm" => "Kerohanian",
            "logo_ukm" => "keluarga-mahasiswa-katolik.png",
            "status_ukm" => "aktif"],
            ["nama_ukm" => "Keluarga Mahasiswa Hindu",
            "jenis_ukm" => "Kerohanian",
            "logo_ukm" => "keluarga-mahasiswa-hindu.png",
            "status_ukm" => "aktif"],
            ["nama_ukm" => "LDK Al-Fath",
            "jenis_ukm" => "Kerohanian",
            "logo_ukm" => "ldk-al-fath.png",
            "status_ukm" => "aktif"],
            ["nama_ukm" => "Telkom University Education Movement",
            "jenis_ukm" => "Sosial",
            "logo_ukm" => "telkom-university-education-movement.png",
            "status_ukm" => "aktif"],
            ["nama_ukm" => "KMPA",
            "jenis_ukm" => "Sosial",
            "logo_ukm" => "kmpa.png",
            "status_ukm" => "aktif"],
            ["nama_ukm" => "Paskibra",
            "jenis_ukm" => "Sosial",
            "logo_ukm" => "paskibra.png",
            "status_ukm" => "aktif"],
            ["nama_ukm" => "Pramuka",
            "jenis_ukm" => "Sosial",
            "logo_ukm" => "pramuka.png",
            "status_ukm" => "aktif"],
            ["nama_ukm" => "Korps Protokoler Mahasiswa (KPM)",
            "jenis_ukm" => "Sosial",
            "logo_ukm" => "kpm.png",
            "status_ukm" => "aktif"]
        ]);
    }
}
