<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class UkmController extends Controller
{
    public function index() {
        $ukmList = [
            ["nama_ukm" => "Telkom University Esports",
            "jenis_ukm" => "Olahraga",
            "logo_ukm" => "telkom-university-esports.png"],
            ["nama_ukm" => "UKM Aceh",
            "jenis_ukm" => "Kesenian & Kebudayaan",
            "logo_ukm" => "ukm-aceh.png"],
            ["nama_ukm" => "AVi Pictures",
            "jenis_ukm" => "Kesenian & Kebudayaan",
            "logo_ukm" => "avi-pictures.png"],
            ["nama_ukm" => "Balon Kata",
            "jenis_ukm" => "Kesenian & Kebudayaan",
            "logo_ukm" => "balon-kata.png"],
            ["nama_ukm" => "UKM Band",
            "jenis_ukm" => "Kesenian & Kebudayaan",
            "logo_ukm" => "ukm-band.png"],
            ["nama_ukm" => "Djawa Tjap Parabola",
            "jenis_ukm" => "Kesenian & Kebudayaan",
            "logo_ukm" => "djawa-tjap-parabola.png"],
            ["nama_ukm" => "Bengkel Seni Embun",
            "jenis_ukm" => "Kesenian & Kebudayaan",
            "logo_ukm" => "bengkel-seni-embun.png"],
            ["nama_ukm" => "Fotografi Telkom",
            "jenis_ukm" => "Kesenian & Kebudayaan",
            "logo_ukm" => "fotografi-telkom.png"],
            ["nama_ukm" => "UKM Kalimantan",
            "jenis_ukm" => "Kesenian & Kebudayaan",
            "logo_ukm" => "ukm-kalimantan.png"],
            ["nama_ukm" => "KBMS",
            "jenis_ukm" => "Kesenian & Kebudayaan",
            "logo_ukm" => "kbms.png"],
            ["nama_ukm" => "UKM Kesenian Bali",
            "jenis_ukm" => "Kesenian & Kebudayaan",
            "logo_ukm" => "ukm-kesenian-bali.png"],
            ["nama_ukm" => "Nippon Bunka-BU",
            "jenis_ukm" => "Kesenian & Kebudayaan",
            "logo_ukm" => "nippon-bunka-bu.png"],
            ["nama_ukm" => "Telkom University Choir",
            "jenis_ukm" => "Kesenian & Kebudayaan",
            "logo_ukm" => "telkom-university-choir.png"],
            ["nama_ukm" => "PERMALA",
            "jenis_ukm" => "Kesenian & Kebudayaan",
            "logo_ukm" => "permala.png"],
            ["nama_ukm" => "Rumah Gadang",
            "jenis_ukm" => "Kesenian & Kebudayaan",
            "logo_ukm" => "rumah-gadang.png"],
            ["nama_ukm" => "SAMALOWA",
            "jenis_ukm" => "Kesenian & Kebudayaan",
            "logo_ukm" => "samalowa.png"],
            ["nama_ukm" => "SAWANDA",
            "jenis_ukm" => "Kesenian & Kebudayaan",
            "logo_ukm" => "sawanda.png"],
            ["nama_ukm" => "Teater Titik",
            "jenis_ukm" => "Kesenian & Kebudayaan",
            "logo_ukm" => "teater-titik.png"],
            ["nama_ukm" => "IMMAPA",
            "jenis_ukm" => "Kesenian & Kebudayaan",
            "logo_ukm" => "immapa.png"],
            ["nama_ukm" => "Telkom University Badminton",
            "jenis_ukm" => "Olahraga",
            "logo_ukm" => "telkom-university-badminton.png"],
            ["nama_ukm" => "UKM Bola",
            "jenis_ukm" => "Olahraga",
            "logo_ukm" => "ukm-bola.png"],
            ["nama_ukm" => "UKM Bola Basket",
            "jenis_ukm" => "Olahraga",
            "logo_ukm" => "ukm-bola-basket.png"],
            ["nama_ukm" => "Capoeira Brazil Telkom University",
            "jenis_ukm" => "Olahraga",
            "logo_ukm" => "capoeira-brazil-telkom-university.png"],
            ["nama_ukm" => "Persatuan Catur Mahasiswa",
            "jenis_ukm" => "Olahraga",
            "logo_ukm" => "persatuan-catur-mahasiswa.png"],
            ["nama_ukm" => "Karate",
            "jenis_ukm" => "Olahraga",
            "logo_ukm" => "karate.png"],
            ["nama_ukm" => "Riverside Softball",
            "jenis_ukm" => "Olahraga",
            "logo_ukm" => "riverside-softball.png"],
            ["nama_ukm" => "PPS Betako Merpati Putih",
            "jenis_ukm" => "Olahraga",
            "logo_ukm" => "pps-betako-merah-putih.png"],
            ["nama_ukm" => "Voli Tel-U / TVBC",
            "jenis_ukm" => "Olahraga",
            "logo_ukm" => "voli-telu.png"],
            ["nama_ukm" => "Teaekwondo",
            "jenis_ukm" => "Olahraga",
            "logo_ukm" => "taekwondo.png"],
            ["nama_ukm" => "Archery Academy of Telkom University",
            "jenis_ukm" => "Olahraga",
            "logo_ukm" => "archatel.png"],
            ["nama_ukm" => "Aksara Jurnalistik",
            "jenis_ukm" => "Penalaran",
            "logo_ukm" => "aksara-jurnalistik.png"],
            ["nama_ukm" => "Central Computer Improvement",
            "jenis_ukm" => "Penalaran",
            "logo_ukm" => "central-computer-improvement.png"],
            ["nama_ukm" => "HIPMI PT",
            "jenis_ukm" => "Penalaran",
            "logo_ukm" => "hipmi-pt.png"],
            ["nama_ukm" => "Indonesia Marketing Association",
            "jenis_ukm" => "Penalaran",
            "logo_ukm" => "ima.png"],
            ["nama_ukm" => "IEEE",
            "jenis_ukm" => "Penalaran",
            "logo_ukm" => "ieee.png"],
            ["nama_ukm" => "KOPMA Tel-U",
            "jenis_ukm" => "Penalaran",
            "logo_ukm" => "kopma-telu.png"],
            ["nama_ukm" => "SEARCH",
            "jenis_ukm" => "Penalaran",
            "logo_ukm" => "search.png"],
            ["nama_ukm" => "SES",
            "jenis_ukm" => "Penalaran",
            "logo_ukm" => "ses.png"],
            ["nama_ukm" => "Persatuan Mahasiswa Kristen",
            "jenis_ukm" => "Kerohanian",
            "logo_ukm" => "persatuan-mahasiswa-kristen.png"],
            ["nama_ukm" => "Keluarga Mahasiswa Katolik",
            "jenis_ukm" => "Kerohanian",
            "logo_ukm" => "keluarga-mahasiswa-katolik.png"],
            ["nama_ukm" => "Keluarga Mahasiswa Hindu",
            "jenis_ukm" => "Kerohanian",
            "logo_ukm" => "keluarga-mahasiswa-hindu.png"],
            ["nama_ukm" => "LDK Al-Fath",
            "jenis_ukm" => "Kerohanian",
            "logo_ukm" => "ldk-al-fath.png"],
            ["nama_ukm" => "Telkom University Education Movement",
            "jenis_ukm" => "Sosial",
            "logo_ukm" => "telkom-university-education-movement.png"],
            ["nama_ukm" => "KMPA",
            "jenis_ukm" => "Sosial",
            "logo_ukm" => "kmpa.png"],
            ["nama_ukm" => "Paskibra",
            "jenis_ukm" => "Sosial",
            "logo_ukm" => "paskibra.png"],
            ["nama_ukm" => "Pramuka",
            "jenis_ukm" => "Sosial",
            "logo_ukm" => "pramuka.png"],
            ["nama_ukm" => "Korps Protokoler Mahasiswa (KPM)",
            "jenis_ukm" => "Sosial",
            "logo_ukm" => "kpm.png"],
        ];

        return view("ukm-list", compact("ukmList"));
    }

    public function tambah() {
        return view("ditmawa.tambah-ukm");
    }

    public function postUkm() {
        return redirect("/ukm")->with("success", "Berhasil menambahkan UKM baru");
    }
}
